import { NextRequest, NextResponse } from "next/server"
import { auth } from "@/lib/auth"
import { prisma } from "@/lib/prisma"

interface ImportProduct {
  sku: string | null
  name: string | null
  pickNumber: string | null
  locationCode: string | null
  category: string | null
  status: string | null
  shopifyProductId: string | null
  shipstationProductId: string | null
}

const VALID_CATEGORIES = ["PLANNER", "NOTEBOOK", "INSERT", "ACCESSORY"]
const VALID_STATUSES = ["ACTIVE", "DISCONTINUED", "DRAFT"]

function normalizeCategory(value: string | null): string {
  if (!value) return "ACCESSORY"
  const normalized = value.toUpperCase().trim()
  if (VALID_CATEGORIES.includes(normalized)) return normalized

  // Try to match common variations
  if (normalized.includes("PLAN")) return "PLANNER"
  if (normalized.includes("NOTE") || normalized.includes("BOOK")) return "NOTEBOOK"
  if (normalized.includes("INSERT")) return "INSERT"
  return "ACCESSORY"
}

function normalizeStatus(value: string | null): string {
  if (!value) return "ACTIVE" // Default to active for imported products
  const normalized = value.toUpperCase().trim()
  if (VALID_STATUSES.includes(normalized)) return normalized

  // Try to match common variations
  if (normalized.includes("ACTIVE") || normalized === "LIVE" || normalized === "ENABLED") return "ACTIVE"
  if (normalized.includes("DISC") || normalized.includes("RETIRED") || normalized.includes("DISABLED")) return "DISCONTINUED"
  if (normalized.includes("DRAFT") || normalized.includes("PENDING")) return "DRAFT"
  return "ACTIVE"
}

function generateSku(index: number): string {
  const timestamp = Date.now().toString(36).toUpperCase()
  const suffix = index.toString().padStart(4, "0")
  return `HO-IMP-${timestamp}-${suffix}`
}

// POST /api/products/import - Import products from CSV
export async function POST(request: NextRequest) {
  try {
    const session = await auth()
    if (!session?.user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const { products } = await request.json() as { products: ImportProduct[] }

    if (!products || !Array.isArray(products)) {
      return NextResponse.json(
        { error: "Invalid request: products array required" },
        { status: 400 }
      )
    }

    if (products.length === 0) {
      return NextResponse.json(
        { error: "No products to import" },
        { status: 400 }
      )
    }

    if (products.length > 5000) {
      return NextResponse.json(
        { error: "Maximum 5000 products per import" },
        { status: 400 }
      )
    }

    // Get existing SKUs to check for duplicates
    const existingSkus = await prisma.product.findMany({
      select: { sku: true }
    })
    const existingSkuSet = new Set(existingSkus.map(p => p.sku))

    // Process products
    const toCreate: any[] = []
    const toUpdate: { sku: string; data: any }[] = []
    const skipped: string[] = []
    let autoGeneratedCount = 0

    for (let i = 0; i < products.length; i++) {
      const product = products[i]

      // Skip products without a name
      if (!product.name?.trim()) {
        skipped.push(`Row ${i + 1}: Missing name`)
        continue
      }

      let sku = product.sku?.trim()

      // Generate SKU if not provided
      if (!sku) {
        sku = generateSku(i)
        autoGeneratedCount++
      }

      const productData = {
        name: product.name.trim(),
        pickNumber: product.pickNumber?.trim() || null,
        locationCode: product.locationCode?.trim() || null,
        category: normalizeCategory(product.category),
        status: normalizeStatus(product.status),
        shopifyProductId: product.shopifyProductId?.trim() || null,
        shipstationProductId: product.shipstationProductId?.trim() || null
      }

      if (existingSkuSet.has(sku)) {
        // Update existing product
        toUpdate.push({ sku, data: productData })
      } else {
        // Create new product
        toCreate.push({ sku, ...productData })
        existingSkuSet.add(sku) // Prevent duplicates within import
      }
    }

    // Perform database operations
    let created = 0
    let updated = 0

    // Create new products in batches
    if (toCreate.length > 0) {
      const batchSize = 100
      for (let i = 0; i < toCreate.length; i += batchSize) {
        const batch = toCreate.slice(i, i + batchSize)
        await prisma.product.createMany({
          data: batch,
          skipDuplicates: true
        })
        created += batch.length
      }
    }

    // Update existing products
    for (const { sku, data } of toUpdate) {
      await prisma.product.update({
        where: { sku },
        data
      })
      updated++
    }

    return NextResponse.json({
      success: true,
      imported: created + updated,
      created,
      updated,
      skipped: skipped.length,
      autoGeneratedSkus: autoGeneratedCount,
      errors: skipped.slice(0, 10) // Return first 10 errors
    })
  } catch (error) {
    console.error("Product import error:", error)
    return NextResponse.json(
      { error: "Failed to import products" },
      { status: 500 }
    )
  }
}
